### ISSUE TITLE
CTD when installed together with Blueshift

### ISSUE THREAD

**Issue by Grimmas** [mockingbirdnest/Principia#3188] opened 2021-11-02 18:55 UTC
KSP immediately crashes to desktop upon starting a new game when only Module Manager, Principia and Blueshift mods are installed.

Reproduction steps (Windows 10):
Install clean stock KSP 1.12.2 and both DLCs.
Install Module Manager version 4.2.1
Install Blueshift version 1.6.2
Install Principia Hadamard with October UI fixes from Google drive link in README.md
Start a new sandbox game with default settings.

I originally thought this may be related to how Blueshift spawns space anomalies (they are functionally similar to asteroids) and this may still be the case, but in my limited testing this issue happened even when space anomaly spawning was turned off in new game difficulty settings.

KSP log doesn't show anything interesting but Principia's stderr.log may hold a clue as it reports a failure from the Euler solver (both logs attached). 

[KSP.log](https://github.com/mockingbirdnest/Principia/files/7463352/KSP.log)
[stderr.log](https://github.com/mockingbirdnest/Principia/files/7463353/stderr.log)

**Comment by pleroy** [comment] 2021-11-02 19:01
These are not the logs that we need, please read https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs.

**Comment by Grimmas** [comment] 2021-11-02 19:14
[The glog files](https://gist.github.com/Grimmas/1fffae6e1d46babb09142f77c02cd060). But both AppData Crashes folders are empty. Anything extra I need to do to get them to populate?

**Comment by eggrobin** [comment] 2021-11-02 19:36
An asteroid is being ill-behaved. I suspect this has something to do with the existence of code in Blueshift that messes with asteroid generation: https://github.com/Angel-125/Blueshift/blob/master/Source/Blueshift/SpaceAnomaly/WBICustomAsteroid.cs.

In any case there is no chance of Blueshift working with Principia: it is an FTL mod, which means it operates by modifying orbits (or positions directly) without applying forces, which will immediately be undone by Principia. See https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#compatibility-with-other-mods.

Closing this as it appear to be a compatibility issue with a mod that is incompatible by design for other reasons anyway.

**Closed by eggrobin** 2021-11-02 19:36 UTC

**Comment by Grimmas** [comment] 2021-11-02 21:38
It's fair to decide not to support FTL mods, even if it's unfortunate, but it shouldn't cause a CTD. That is a poor user experience. If it's not fixable then I would suggest to at least add Blueshift to the list of known incompatible mods in the README with a warning about potential crashes.

**Comment by eggrobin** [comment] 2021-11-02 21:58
> it shouldn't cause a CTD. That is a poor user experience.

The CTD is not due to Blueshift being an FTL mod, it is due to Blueshift violating invariants that we expect from KSP. Violations of invariants result in an immediate crash, because otherwise they would instead result in broader save corruption and hard-to-diagnose bugs.

This would be a bug that should be raised with Blueshift if Blueshift were compatible; it just happens that it isn’t, so there is no point in doing so.

As for listing incompatibilities, this falls into the category
> Any mod that tries to move vessels or otherwise change orbits either (1) without using engines or (2) during time warp, is incompatible with Principia.

documented in the FAQ. To quote the next paragraph,
> Many mods do that, and they are as a consequence all incompatible with Principia. We document some high-profile incompatibilities below, but we cannot really know about all of them. Mod users are advised to think about possible incompatibilities when using multiple mods.

(to wit, we had never heard about Blueshift before this issue).

**Comment by pleroy** [comment] 2021-11-02 22:11
Note that there is indeed a space anomaly, and I suspect that it is the part that's causing trouble:
```
I1102 20:08:28.900532 16644 vessel.cpp:111] Adding part wbiTet (00000000) to vessel UNK-BBV-294 (f95c4596-b4bb-4853-8d06-15fcfe501ac7)
```
This can be found here: `WildBlueIndustries/Blueshift/Parts/SpaceAnomalies/Tet/tetrahedron`.  It's not overly surprising that a nonphysical part would break Principia.
