### ISSUE TITLE
Set Orbit in the debug menu does not work

### ISSUE THREAD

**Issue by maccollo** [mockingbirdnest/Principia#1420] opened 2017-05-31 23:46 UTC
When Principia is running on the current vessel you can't use the Set Orbit menu without force stopping Principia.

**Comment by eggrobin** [comment] 2017-06-01 07:27
That is a known effect of Principia; anything that tries to modify the orbit (including HyperEdit, the debug menu orbit setter, the orbital decay mod) will have no effect. I don't think we intend to do anything about this (for the specific case of the orbital decay mod we have the same aims, since the author intends to support n-body gravitation eventually, and I'd like to support orbital atmospheric drag eventually).

**Comment by pleroy** [comment] 2017-06-02 20:41
Closing as this is working as intended.

**Closed by pleroy** 2017-06-02 20:41 UTC
Labels: wontfix
