### ISSUE TITLE
KSP 1.8.1 - Aerodynamic issue with Principia and FAR

### ISSUE THREAD

**Issue by ArrowMaxGithub** [mockingbirdnest/Principia#2562] opened 2020-05-08 16:04 UTC
Mods in question:
FAR continued - 0.15.11.4
Principia - 'Fubini' for KSP 1.8.1 and 1.9.0

Additional mods and dependencies:
Real Solar System - 18.0
Kopernicus Planetary System Modifier - 1.8.1.1
Module Manager - 4.1.3
Modular Flight Integrator - 1.2.7.0

Issue:
With both FAR continued and Principia installed, any change in flight controls will result in a short 'kick'.
Example GIF:
![FAR and Principia](https://user-images.githubusercontent.com/60489413/81424253-f2348f80-9155-11ea-80cb-7827c6f0bcef.gif)

On the same install, but without Principia, the motion is smooth.
Example GIF:
![FAR alone](https://user-images.githubusercontent.com/60489413/81424260-f52f8000-9155-11ea-8ccc-e3b4ff03491d.gif)

Steps that lead to this issue:
1) Fresh install of KSP 1.8.1
2) CKAN install of RSS and FAR continued with all dependencies
3) Manual install of Principia
4) Flying any aircraft or rocket will show the jerky motion

**Comment by dkavolis** [comment] 2020-05-08 16:13
Likely related to #2519 as there's no jerking when using Frenet

**Comment by eggrobin** [comment] 2020-05-08 23:33
As @dkavolis says, this looks very much like #2519.

Can you try the test build given in https://github.com/mockingbirdnest/Principia/issues/2519#issuecomment-626062713 tell us what happens?

**Comment by ArrowMaxGithub** [comment] 2020-05-09 05:37
The jerking motion persists, but it appears to be somewhat dampened.
But there is a new issue in form of an oscillation that occurs regardless of user input or craft stability.

Both with and without FAR.

Example video of the test build plus FAR:
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/60489413/81465094-a7ebf680-91c7-11ea-939e-5a96664e509a.gif)

**Comment by pleroy** [comment] 2020-05-12 21:11
Marking as a duplicate of #2519, follow the progress there.

**Comment by pleroy** [comment] 2020-06-05 06:48
Fixed in Fuchs, closing.

**Closed by pleroy** 2020-06-05 06:48 UTC
Labels: bug, duplicate

**Comment by pleroy** [comment] 2020-06-20 10:51
Actually turned out to be an instance of #2560.

**Comment by eggrobin** [comment] 2020-06-20 18:28
> Actually turned out to be an instance of #2560.

I don’t think it was; the oscillations shown in the animations are clearly Fubini-type oscillations, rather than the "unbalanced aircraft" situation that #2560 caused; the engines used there don’t have the massive centre of mass offset of the rapier.
