### ISSUE TITLE
KSP (Unity) crashes during staging 

### ISSUE THREAD

**Issue by jovanhadziristic** [mockingbirdnest/Principia#4030] opened 2024-07-01 13:52 UTC
I did not find Principia logs so updated ksp logs... Fresh install of the game 1.12.3 and 1.12.5 have the same issue + express install for RP/RO via CKAN for 1.12.3, manual RP/RO/Real Solar install for 1.12.5

It keeps crashing during staging and every time logs show the following:
![image](https://github.com/mockingbirdnest/Principia/assets/96573760/584a8bfe-49a7-4a4c-9863-c8296d26ec23)

[KSP_logs.zip](https://github.com/user-attachments/files/16053562/KSP_logs.zip)

**Comment by jovanhadziristic** [comment] 2024-07-01 14:40
Principia logs: 
[Principia_log.zip](https://github.com/user-attachments/files/16054461/Principia_log.zip)

**Comment by jovanhadziristic** [comment] 2024-07-01 15:10
> That said, this feels like https://github.com/mockingbirdnest/Principia/issues/4026.

![image](https://github.com/mockingbirdnest/Principia/assets/96573760/446f4094-51d1-4aad-abc9-ae88df51813e)
Had another crash, here is the screenshot. Looks the same as the other tread.

**Comment by pleroy** [comment] 2024-07-01 15:54
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/9fb31039dab1a147e9f302f3f333341117983056/ksp_plugin/interface.cpp#L886-L890

**Comment by pleroy** [comment] 2024-07-01 15:55
Duplicate of #4026.

**Closed by pleroy** 2024-07-01 15:55 UTC
