### ISSUE TITLE
Game hangs deleting duplicate flight plan

### ISSUE THREAD

**Issue by lpgagnon** [mockingbirdnest/Principia#3782] opened 2023-10-23 00:49 UTC
Initial state: in transfer orbit with flight plan to perform circularization burn to geostationary

steps: 3 mouse clicks: Duplicate the flight plan, Delete the maneuver, Delete the flight plan.
result: game hangs. no crash, just complete UI freeze, game must be terminated manually. (audio keeps going though)

deleting without duplicating is fine.

interesting bits of error.log, matching time of freeze:
```
E1022 20:40:42.578752 42250880 interface_body.hpp:484] Reached maximum step count 4096 at time 1955-07-15T22:54:47,0044832229614258 (TT); requested t_final is 1955-07-29T09:31:47,4859068393707275 (TT).
E1022 20:40:42.958879 3438059520 matrix_computations_body.hpp:479] Difficult diagonalization: rows: 4 columns: 4
[snip]
```

bug is 100% reproducible; journal (and logs) attached (10MB zipped, 38MB unzipped).
[principia_hang.zip](https://github.com/mockingbirdnest/Principia/files/13065050/principia_hang.zip)

extra oddity; after creating journal, killing the game and restarting it, journaling was enabled from the start. not sure if that's deliberate; could have done bad things to my drive if I hadn't noticed.

**Comment by pleroy** [comment] 2023-10-25 19:58
Thank you, Mario!  But our bug fix is in [another branch](https://github.com/mockingbirdnest/Principia/commit/f7d6c7e8d4b8e4e2943048728f59808bdd5994d5)!

(Turns out that we found the bug, but we fixed in it the branch that has flight plan optimization, and that branch is not merged yet.)

**Closed** 2023-10-25 20:33 UTC

**Comment by pleroy** [comment] 2023-10-26 17:15
I forgot to reply regarding "journaling was enabled from the start".  This is by design, it has proven helpful to debug problems that happen very early when starting the mod/loading the save.  If you forgot to disable journaling, slap yourself in the face.
