### ISSUE TITLE
Crash to desktop when attempting to enter Tracking Station

### ISSUE THREAD

**Issue by eecano** [mockingbirdnest/Principia#4113] opened 2024-10-11 19:59 UTC
Hello I have an issue where after installing RO/RSS using their express install on CKAN, I install principia, start a new game, I get a crash to desktop anytime I try to access the tracking station. When I uninstall Principia I can access the Tracking station just fine. I have reinstalled everything, DDU'd my display drivers, moved to a clean folder outside steam, verified enough memory,  and placed page file on auto as troubleshooting steps. I also removed all additional mods except the express RO install to see if those were causing issues. I am attaching all logs I could find.

[Crash Files.zip](https://github.com/user-attachments/files/17347002/Crash.Files.zip)

**Comment by pleroy** [comment] 2024-10-11 20:22
Probably [this known issue](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#known-issues).

**Comment by eecano** [comment] 2024-10-11 21:01
> Probably [this known issue](https://github.com/mockingbirdnest/Principia/wiki/Change-Log#known-issues).

Thanks, I followed the link and downloaded and installed the latest version of C++ and still get a CTD when entering tracking stations.

**Comment by eggrobin** [comment] 2024-10-11 22:57
Well, the logs show that this was indeed a duplicate of https://github.com/mockingbirdnest/Principia/issues/4088, and that you have the exact same version 14.29.30133.0 of MSVCP140.

If you are still encountering a crash, either it is a different issue, for which you would need to provide new logs, or you are somehow still using the old C++ x64 runtime.

**Closed by eggrobin** 2024-10-11 22:57 UTC
