### ISSUE TITLE
Appending before fork time

### ISSUE THREAD

**Issue by barcharcraz** [mockingbirdnest/Principia#2490] opened 2020-03-12 16:37 UTC
Log file created at: 2020/03/12 09:09:17
Running on machine: DESKTOP-68GQI37
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFE864D6360  	google::LogMessageFatal::~LogMessageFatal [0x00007FFE864D635F+47]
    @   00007FFDF96788CC  	(No symbol) [0x00007FFDF96788CB]
    @   00007FFDF984E857  	principia__VesselVelocity [0x00007FFDF984E856+1276966]
    @   00007FFDF984DF85  	principia__VesselVelocity [0x00007FFDF984DF84+1274708]
    @   00007FFDF97F00B5  	principia__VesselVelocity [0x00007FFDF97F00B4+889988]
    @   00007FFDF96E7998  	principia__CatchUpLaggingVessels [0x00007FFDF96E7997+231]
    @   00000203C9FFAA17  	(No symbol) [0x00000203C9FFAA16]
F0312 09:09:17.425650 28596 discrete_trajectory_body.hpp:170] Check failed: this->is_root() || time > this->Fork()->time Append at +6.25980497443201148e+03 s which is before fork time +6.26290882815326040e+03 s

I get these errors when seperating stages. I'm running quite a few mods which I understand could be an issue. Running Frenet on 1.8.1

**Comment by pleroy** [comment] 2020-03-12 16:41
Could you please give us your save and your logs?  See the [FAQs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs) for instructions.

**Comment by barcharcraz** [comment] 2020-03-12 18:05
[ERROR.20200312-093359.30344.log](https://github.com/mockingbirdnest/Principia/files/4325735/ERROR.20200312-093359.30344.log)
[FATAL.20200312-093515.30344.log](https://github.com/mockingbirdnest/Principia/files/4325736/FATAL.20200312-093515.30344.log)
[INFO.20200312-092649.30344.log](https://github.com/mockingbirdnest/Principia/files/4325737/INFO.20200312-092649.30344.log)
[WARNING.20200312-093359.30344.log](https://github.com/mockingbirdnest/Principia/files/4325739/WARNING.20200312-093359.30344.log)
[KSP.log](https://github.com/mockingbirdnest/Principia/files/4325745/KSP.log)

**Comment by barcharcraz** [comment] 2020-03-12 18:06
[181real6.zip](https://github.com/mockingbirdnest/Principia/files/4325750/181real6.zip)

**Comment by barcharcraz** [comment] 2020-03-12 19:21
Would it be helpful to try using the latest version from master?

**Comment by pleroy** [comment] 2020-03-12 19:32
For our information, the decoded stack:

 https://github.com/mockingbirdnest/Principia/blob/f9d1326d0876eee1212c6ff0db0a98b628f46277/ksp_plugin/interface.cpp#L346-L351  https://github.com/mockingbirdnest/Principia/blob/f9d1326d0876eee1212c6ff0db0a98b628f46277/ksp_plugin/plugin.cpp#L749-L776  https://github.com/mockingbirdnest/Principia/blob/f9d1326d0876eee1212c6ff0db0a98b628f46277/ksp_plugin/vessel.cpp#L233-L243  https://github.com/mockingbirdnest/Principia/blob/f9d1326d0876eee1212c6ff0db0a98b628f46277/ksp_plugin/vessel.cpp#L579-L618  https://github.com/mockingbirdnest/Principia/blob/f9d1326d0876eee1212c6ff0db0a98b628f46277/physics/discrete_trajectory_body.hpp#L169-L170

**Comment by pleroy** [comment] 2020-03-12 19:34
> Would it be helpful to try using the latest version from master?

I don't think so.  There has been no change in this code since Frenet that would cause the bug to magically go away.

**Comment by barcharcraz** [comment] 2020-03-12 20:29
Interestingly this happened twice for me, so I suspect that some mod I'm running is making this bug much more likely.

**Comment by pleroy** [comment] 2020-03-18 21:57
I have a hunch that some mod is creating parts out of step with the normal lifecycle of the game, and that this breaks one of our invariants.  There are many messages like the following in your logs:
```
E0312 09:33:59.783618  5448 ksp_plugin_adapter.cs:966] Unpacked part mk1pod.v2 (7ACCEF60) appeared between BetterLateThanNever and WaitForFixedUpdate.  Linearly extrapolating its position at the previous frame.
```
At this point it would be useful to have a journal of the actions made by Principia.  To do that, open `Logging Settings` in the main Principia window and select `Record journal (starts on load)` at the bottom left.  Do a scene change to make sure that journaling is enabled (you should see `Journaling is ON` at the bottom right).  Then try to reproduce the problem.  If/when it fails again, send us the log files and the journal files found in your `glog` directory.

Journaling will make the game quite slow.  Be sure to disable it once you've sent us the journal.

**Comment by pleroy** [comment] 2020-03-31 06:36
Duplicate of #2507.  Follow the music there.

**Closed by pleroy** 2020-03-31 06:37 UTC
Labels: bug, duplicate
