### ISSUE TITLE
Crash when the plotting frame is set to MCMF

### ISSUE THREAD

**Issue by kscarvajalc** [mockingbirdnest/Principia#3872] opened 2024-02-10 23:23 UTC
So, I was trying to land in the Mun but the moment I changed to the surface reference frame the game crashed with a window from Visual C++, the crash happens every time the trajectory intersects with the surface no matter if it is a flight plan, the actual landing or the tracking station.

https://gist.github.com/kscarvajalc/bbc5364f9884ea1b2ceb74a0dd4743c6

**Comment by pleroy** [comment] 2024-02-11 11:10
Thanks for reporting.  Do you by any chance have a crash folder in `%USERPROFILE%\AppData\Local\Temp\Squad\Kerbal Space Program\Crashes`?  If so, could you zip it and send it to us?

The journal does indeed indicate a failure in the new impact computation code, but I am unable to reproduce the crash.  That may not be too surprising since the problem looks like some kind of memory corruption and these things are hard to reproduce.  The crash dump could give us some hints.

**Comment by kscarvajalc** [comment] 2024-02-11 19:22
No, there are no folders related to that crash

**Comment by pleroy** [comment] 2024-02-13 20:44
If you are able to reproduce the crash, could you give us your `KSP.log` file immediately after the crash?  (Note that this file gets overwritten each time you start the game, so it's important to get the one that corresponds to the crash.)

**Comment by kscarvajalc** [comment] 2024-02-14 21:20
I was able to reproduce the crash, curiously this time the trajectory wasn't suborbital, just very eccentric.

https://gist.github.com/kscarvajalc/3a530b7fc09b536f9e9f7746545324e0

**Comment by pleroy** [comment] 2024-05-25 13:03
The files in the latest reply don't contain any crash.  We didn't hear about any bug in this code since #3882 and #3959, so I am closing this issue.

**Closed by pleroy** 2024-05-25 13:03 UTC

**Comment by kscarvajalc** [comment] 2024-08-14 03:08
Hello, I couldn't update the report, the problem persist with the same dialog as the seen in #4038 for all the releases until Klein. Today, I updated the mod, and the crash when the vessel is in suborbital trajectory is solved, but still crashes when the periapsis is close to the ground and the plotting frame is MCMF, with the difference that the game just freezes with no dialog. Also I think the crash happened when I tried to start the engine.

[ERROR.20240813-192650.7288.log](https://github.com/user-attachments/files/16606834/ERROR.20240813-192650.7288.log)
[WARNING.20240813-192650.7288.log](https://github.com/user-attachments/files/16606835/WARNING.20240813-192650.7288.log)
[INFO.20240813-192650.7288.log](https://github.com/user-attachments/files/16606836/INFO.20240813-192650.7288.log)
[JOURNAL.zip](https://github.com/user-attachments/files/16607208/JOURNAL.zip)
[Player.log](https://github.com/user-attachments/files/16606966/Player.log)

Like the last time, there is no crash folder.

**Comment by pleroy** [comment] 2024-08-15 07:44
(I didn't realize that there was a windows from the C++ Runtime Library in the original report.  A screenshot would have been helpful.)

I am marking this issue as a duplicate, let's continue the discussion in #4038.
