### ISSUE TITLE
Game crashes when loading a savefile

### ISSUE THREAD

**Issue by von-Kerman** [mockingbirdnest/Principia#3331] opened 2022-02-16 20:27 UTC
Game consistently crashes to desktop when loading the attached savefile. No dialog windows are shown.
Nothing appears in \AppData\Local\Temp\Squad\Kerbal Space Program\Crashes. There is no new folder with current crash date.
There are errors in Principia logs FATAL and INFO.

F0216 23:20:43.390908  1376 push_deserializer_body.hpp:119] Check failed: message_->ParseFromCodedStream(&decoder) 
E0216 23:20:43.389940  1376 interface.cpp:698] [C:\Users\phl\Projects\GitHub\Principia\Google\protobuf\src\google\protobuf\io\coded_stream.cc:192] A protocol message was rejected because it was too big (more than 536870912 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in net/proto2/io/public/coded_stream.h.

[persistent.zip](https://github.com/mockingbirdnest/Principia/files/8083260/persistent.zip)
[INFO.20220216-232008.2468.log](https://github.com/mockingbirdnest/Principia/files/8083270/INFO.20220216-232008.2468.log)
[FATAL.20220216-232043.2468.log](https://github.com/mockingbirdnest/Principia/files/8083271/FATAL.20220216-232043.2468.log)

**Comment by pleroy** [comment] 2022-02-16 22:56
You have a corrupted save.  Sad, but not much that can be done (surely you have backups?).  The error about a 512 MiB protocol message is a red herring: because the save is corrupted, it finds somewhere a size field that contains an overly large value and refuses to parse the message.  If the size field was smaller it would try to parse it and fail in a differently mysterious manner.

Because our saves are binary compressed data, a bit flip will have far-reaching consequences that will typically make the save unusable.  This wouldn't happen if we were using uncompressed text, but that would cause other inconveniences.

**Comment by von-Kerman** [comment] 2022-02-19 16:07
I've managed to journal the save corruption. It happens as follows: 
- load the game "persistent (before corruption).sfs"
- switch to vessel "0032_Mars-Equator"
- do some maneuvers with it (orient to the Sun, coast until the node, change inclination to roughly match Phobos)
- switch back to KSC, the game crashes during the switch

https://drive.google.com/file/d/14fkax2VK4mDjBTtD1Mf-qJplWuixfwtb/view?usp=sharing

**Comment by dgeastman** [comment] 2022-06-10 01:37
I'm having the same issue, my game crashed to desktop last night while switching back to KSC from a Mars orbiter, and now the save won't load. The fact that this happened to both of us after maneuvers at Mars is interesting.https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by pleroy** [comment] 2022-06-28 19:32
Probably a duplicate of #3375.

**Closed by pleroy** 2022-06-28 19:32 UTC
Labels: duplicate
