### ISSUE TITLE
Game crashes on load of a save.

### ISSUE THREAD

**Issue by Sanchez-1** [mockingbirdnest/Principia#3439] opened 2022-09-16 02:57 UTC
Hi there so basically I'm running the newest KSRSS Reborn and everything works perfect until I installed Principia. This was my log file for the fatal error that closes the game out right on load of a save. (I would have put it on gist but since it was so small I figured pasting it worked aswell). I know it has configs for Principia and I have zero clue what the error means to understand it, any help would be great.

```
Log file created at: 2022/09/15 18:27:05
Running on machine: ************
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FFA7FD0443F  	google::LogMessageFatal::~LogMessageFatal [0x00007FFA7FD0443E+46]
    @   00007FFA1CD69711  	principia__VesselVelocity [0x00007FFA1CD69710+1048848]
    @   00007FFA1CC38DA7  	principia__InsertUnloadedPart [0x00007FFA1CC38DA6+646]
    @   00000271D8CABAB7  	(No symbol) [0x00000271D8CABAB6]
F0915 18:27:05.842931 19160 plugin.cpp:1645] Check failed: inserted part_id: 3080220487
```

**Comment by Sanchez-1** [comment] 2022-09-21 21:41
B u m p

**Comment by pleroy** [comment] 2022-09-25 13:17
Well, you can bump all you want but you didn't give us the INFO log as instructed by the [FAQs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt) so as it stands this bug report is unusable.

This being said this kind of crash has been seen with mods that violate the invariants of KSP and create two parts with the same id.  In some cases we have been able to work with the mod author to resolve the issue.  The first order of business would be for you to figure out which mod is incompatible with Principia (e.g., by removing them one by one and trying to reproduce the bug).

**Comment by amoraschi** [comment] 2022-11-20 00:07
> Well, you can bump all you want but you didn't give us the INFO log as instructed by the [FAQs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt) so as it stands this bug report is unusable.
> 
> This being said this kind of crash has been seen with mods that violate the invariants of KSP and create two parts with the same id. In some cases we have been able to work with the mod author to resolve the issue. The first order of business would be for you to figure out which mod is incompatible with Principia (e.g., by removing them one by one and trying to reproduce the bug).

Can confirm that the issue is produced by Principia, since it doesn't appear when I don't have it instealled. As requested, these are the last `FATAL` and `INFO` logs:

https://gist.github.com/amoraschi/b8e985ae822757ff78ee1904c6608899

Bump...

**Comment by eggrobin** [comment] 2022-11-20 00:42
@amoraschi, your issue is unrelated to Sanchez’s; your FATAL log has the error
```
F1120 00:47:01.671447 11384 map_util.hpp:58] Check failed: it != collection.end() Map key not found: 34
```
whereas Sanchez’s has
```
F0915 18:27:05.842931 19160 plugin.cpp:1645] Check failed: inserted part_id: 3080220487
```
Your issue is likely due to changing the solar system on an existing save. Principia does not support that; make a new save if you add bodies to the solar system.

Specifically, the body with `flightGlobalsIndex` 34 is not found (a cursory GitHub search finds than RSSExpansion [assigns that index to 21 Lutetia](https://github.com/zilti/RSSExpansion/blob/1c4324131bc9da6b945f04ef54cf000dfa7e7dfe/RSSExpansion/RSSExpansionBodies/Asteroids/Lutetia.cfg#L9-L11)).

---
Decoded stack trace:
 https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/ksp_plugin/interface.cpp#L1210-L1215  https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/ksp_plugin/plugin.cpp#L307-L309  https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/base/map_util.hpp#L56-L58

**Comment by amoraschi** [comment] 2022-11-20 00:54
> @amoraschi, your issue is unrelated to Sanchez’s; your FATAL log has the error
> ```
> F1120 00:47:01.671447 11384 map_util.hpp:58] Check failed: it != collection.end() Map key not found: 34
> ```
> whereas Sanchez’s has
> ```
> F0915 18:27:05.842931 19160 plugin.cpp:1645] Check failed: inserted part_id: 3080220487
> ```
> Your issue is likely due to changing the solar system on an existing save. Principia does not support that; make a new save if you add bodies to the solar system.
> 
> Specifically, the body with `flightGlobalsIndex` 34 is not found (a cursory GitHub search finds than RSSExpansion [assigns that index to 21 Lutetia](https://github.com/zilti/RSSExpansion/blob/1c4324131bc9da6b945f04ef54cf000dfa7e7dfe/RSSExpansion/RSSExpansionBodies/Asteroids/Lutetia.cfg#L9-L11)).
> 
> ---
> Decoded stack trace:
>  https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/ksp_plugin/interface.cpp#L1210-L1215  https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/ksp_plugin/plugin.cpp#L307-L309  https://github.com/mockingbirdnest/Principia/blob/effff1495717bafe6d9c2336caec3c0a193fa182/base/map_util.hpp#L56-L58 
> 

Strange, I'm just using KSRSS Reborn just like Sanchez, I'm not changing the solar system on an existing save and I'm not using RSS.

Did you mean that to use Principia I need to start a new save?

**Comment by eggrobin** [comment] 2022-11-20 01:04
> Did you mean that to use Principia I need to start a new save?

At this point, yes (this is [recommended in the FAQ](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#my-vessels-are-all-over-the-place) for a number of other reasons anyway).

> I'm not changing the solar system on an existing save and I'm not using RSS (KSRSS does import things from RSS Expansion tho)

The likely scenario here is that at some point you opened the save with Principia installed and without body 34 (which created the Principia save state for a system without body 34), then added whichever mod adds body 34, and opened the save again.

**Comment by pleroy** [comment] 2022-12-18 10:56
Closing as the OP never provided logs and the second issue was properly resolved.

**Closed by pleroy** 2022-12-18 10:56 UTC
