### ISSUE TITLE
Terrible framerate in map view

### ISSUE THREAD

**Issue by oowoohoo** [mockingbirdnest/Principia#1487] opened 2017-07-30 19:24 UTC
I am running an RP-0/RO save with principia, and upon entering orbit where my trajectories are displayed, the framerate drops to nearly unplayable levels.  Is there a fix?

Mods:
KSP: 1.2.2 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
Toolbar - 1.7.13
Advanced Jet Engine - 2.8
B9 Aerospace Procedural Parts - 0.40.11
Community Resource Pack - 0.6.6
CommunityTechTree - 3.0.3
Connected Living Space - 1.2.4.2
Contract Configurator - 1.22.2
CustomBarnKit - 1.1.12
Deadly Reentry - 7.6.0.1
Ferram Aerospace Research - 0.15.8.1
Firespitter - 7.5.1
Kerbal Construction Time - 1.3.9
Kerbal Joint Reinforcement - 3.3.2
KSP-AVC Plugin - 1.1.6.2
MagiCore - 1.2.5
ModularFlightIntegrator - 1.2.4
Procedural Parts - 1.2.11
RCS Build Aid - 0.9.1
RealChute - 1.4.3
RealismOverhaul - 11.5.1
RealSolarSystem - 12.0
RemoteTech - 1.8.6
RetractableLiftingSurface - 0.1.3
RSSDateTime - 1.1
Saturatable RW - 1.12
SCANsat - 1.1.6.11
Ship Manifest - 5.1.3.3
SolverEngines - 3.1
SXTContinued - 0.3.12.1
TAC Life Support - 0.13
TweakScale - 2.3.4
VenStockRevamp - 1.9.5

**Comment by pleroy** [comment] 2017-07-30 20:20
Could you share your save with us, e.g., as a gist here on github?  It would be really helpful in trying to understand what the problem is.

There is a known problem in map view, where all the time is spent plotting the past trajectory (history).  We have been working on fixing it for a few months (see #973) and the fix will likely be in the next version, Чебышёв, to be released on August 21.  In the meantime the work-around is to make the history as short as possible (there are controls to do that in the Principia panel).

**Comment by pleroy** [comment] 2017-07-31 15:40
I made a small save with a rocket taking off and flying for about 12 minutes.  In Cayley (the current version) in map view showing the full history reduces the frame rate to 5 fps.  After #1493 the frame rate goes up to 30 to 60 fps depending on the viewpoint.

**Comment by oowoohoo** [comment] 2017-07-31 20:55
Here is my save.

[The Real Deal.zip](https://github.com/mockingbirdnest/Principia/files/1188815/The.Real.Deal.zip)

**Comment by eggrobin** [comment] 2017-08-06 12:38
Fixed by #1506 (as mentioned in the issue, this improves framerate from 8 fps to 55 fps in the tracking station for a pathological example).
The fix will be in Чебышёв, to be released on 2017-08-21.

**Closed by eggrobin** 2017-08-06 12:38 UTC
Labels: enhancement
