### ISSUE TITLE
Principia doesn't plot trajectories of vessels that don't have control parts

### ISSUE THREAD

**Issue by scimas** [mockingbirdnest/Principia#1599] opened 2017-10-13 09:41 UTC
It doesn't plot trajectory of a vessel which doesn't have a part from which the vessel can be controlled, when the vessel is active. ie, it does plot trajectories in tracking center but not when you're actually using the vessel. Tested in 1.3.0 build, don't know about 1.2.2.
As an example any ejected stage of a rocket will suffice to demonstrate this.
Ignore this if its an intended change, but I don't remember reading it in change log.

**Comment by eggrobin** [comment] 2017-10-13 18:07
I am unable to reproduce this issue; do you have a stock save that exhibits it?

**Comment by scimas** [comment] 2017-10-13 22:15
That's strange. It happened with two of my ships back to back and so I assumed it was happening with everyone of them. But now I am unable to reproduce it too. And unfortunately I don't have those save files either. Apologies for the false alarm.

**Comment by pleroy** [comment] 2017-12-10 16:31
Closing as this couldn't be reproduced for some time.

**Closed by pleroy** 2017-12-10 16:31 UTC
Labels: bug, not reproducible
