### ISSUE TITLE
Frequent crashes on stage after loading a game

### ISSUE THREAD

**Issue by mmomtchev** [mockingbirdnest/Principia#3855] opened 2024-01-26 23:48 UTC
I have frequent crashes when staging with the same stack trace as #3802
Here is the last part of the logs: https://gist.github.com/mmomtchev/d13a2dca27ab78cfffdf0c32e3c54525

These always happen in the same situation: if I launch a vessel, then save the game, exit it and load it back, it will crash when staging. If I don't stage this particular vessel, I can continue normally. Loading a previous save and launching the same vessel again fixes it too as long as I do not quite the game. I never had a crash outside of this situation and when it happens in this situation, it is always 100% reproducible.

RP-1 with Julia, standard CKAN install, I had this with the previous version as well.

**Comment by mmomtchev** [comment] 2024-01-27 09:34
It may be related to the vessel having a scientific core in its root stage.

**Comment by pleroy** [comment] 2024-07-03 17:36
Probably a duplicate of #4026.

**Closed** 2024-07-04 20:16 UTC
Labels: duplicate
