### ISSUE TITLE
crash on minmus

### ISSUE THREAD

**Issue by agustincaniglia** [mockingbirdnest/Principia#1618] opened 2017-11-05 00:15 UTC
I got to Minmmus, and landed. When I tried to go away from the surface, the game crashed.

Here is the glog archives: https://www.dropbox.com/s/yn3i35y8vkhn4cj/Principia.rar?dl=0

And here is the KSP.log https://www.dropbox.com/s/lq9jcl4o4m72yiw/KSP.rar?dl=0

**Comment by eggrobin** [comment] 2017-11-05 00:47
Stack trace:
```
    @   000007FEEBC343C5  	principia__GetPlottingFrame [0x000007FEEBC343C4+230920]
    @   000007FEEBB9F13B  	principia__FlightPlanCreate [0x000007FEEBB9F13A+572970]
    @   000007FEEBBF5744  	principia__LogFatal [0x000007FEEBBF5743+111]
    @   000000013F363F0D  	(No symbol) [0x000000013F363F0C]
F1104 20:43:12.629523  1628 interface.cpp:668] System.NullReferenceException: 

  at (wrapper managed-to-native) UnityEngine.Component:get_gameObject ()

  at principia.ksp_plugin_adapter.PrincipiaPluginAdapter+<AdvanceAndNudgeVesselsAfterPhysicsSimulation>d__105.MoveNext () [0x00000] in <filename unknown>:0 
```
So this is an exception somewhere in the `WaitForFixedUpdate` block. This usually hard to track, fortunately we have one level of managed stack, which tells us we are getting the `gameObject` property.
That seems to narrow it down to either reference to `collider.gameObject`.
There is a null check before the second one (which was added to fix the very similar #1447), but the first one was added (in Chasles) before that null check; moving it down should resolve this issue.

**Comment by agustincaniglia** [comment] 2017-11-07 20:43
Moving it down? SOrry I don't understand much, was just trying to help, but I keep having CTDs in situations like EVA trying to enter cockpits, or transitions between surface and space...

**Comment by eggrobin** [comment] 2017-11-07 20:47
The above was a note to ourselves, describing what we need to do to solve this issue. No action is required on your part.

**Comment by agustincaniglia** [comment] 2017-11-07 21:08
OK, Here I have more logs in case it is helpful. This time tying to enter my cabin in space near mun.
https://www.dropbox.com/s/yn3i35y8vkhn4cj/Principia.rar?dl=0

**Closed** 2017-11-12 15:03 UTC
Labels: bug

**Comment by scimas** [comment] 2017-11-13 21:42
Probably the same bug. The vessel on which the crash happened was Polar Mun Lander. Can't reproduce the bug on demand though.
[bug_report.zip](https://github.com/mockingbirdnest/Principia/files/1468715/bug_report.zip)
