### ISSUE TITLE
Switching between vessels does not update maneuver node.

### ISSUE THREAD

**Issue by Thomas-P** [mockingbirdnest/Principia#1565] opened 2017-09-17 19:04 UTC
When I switch from one vessel to another, with an active maneuver plan, the node for this maneuver isn't the one that is planned next. I have to reactivate the show maneuver in navball checkbox to update the maneuver into the right direction.

**Comment by scimas** [comment] 2017-11-05 19:41
Just wanted to add that the manoeuvre node is also sometimes not updated (deleted) if you delete a flight plan before executing any of the nodes in it.

**Comment by scimas** [comment] 2017-12-17 20:33
There is another related bug to this (or maybe they have a common cause). Manoeuvre node isn't updated by principia if flight plan window is not open (even if show on navball was selected before closing the window).
Not sure whether it needs a separate issue of its own.

**Comment by pleroy** [comment] 2019-04-13 16:33
Note to self: I was in this code recently and restructured it a bit in #2131.  The root of the problem is that the (new) method `FlightPlanner.ShowGuidance` is only called when rendering the flight plan window so if that window is hidden, or the flight plan is deleted, or a different vessel is selected, the guidance node is likely to be left alone until someone clicks "Show on navball" again.

**Closed** 2019-04-17 19:36 UTC
Labels: bug
