### ISSUE TITLE
Hard CTD when using the slider to change the tangent after modifying the initial time using its slider.

### ISSUE THREAD

**Issue by daantimmer** [mockingbirdnest/Principia#2867] opened 2021-01-19 23:10 UTC
INFO -> https://gist.github.com/daantimmer/a48d2b44437c76324bbd808e43d6493e
FATAL -> https://gist.github.com/daantimmer/f3f673a35f575b63f1406f6e0427b412

I was creating the initial flight plan of a newly launched vessel.
I first modified initial time of maneouver.
Then I tried to modify the Tangent and the moment I clicked the slider the game did a hard CTD.

**Comment by daantimmer** [comment] 2021-01-20 14:15
Same steps, new crash. INFO + FATAL -> https://gist.github.com/daantimmer/bc5136a011209d974c5a487dfa0290cf

**Comment by daantimmer** [comment] 2021-01-20 14:15
Same steps, new crash. INFO + FATAL -> https://gist.github.com/daantimmer/0d8a2ecbbe18dff6892448b354adeba7

**Comment by pleroy** [comment] 2021-01-23 10:55
Decoded stack trace for the first crash:
 https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/base/jthread_body.hpp#L171-L171  https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/ksp_plugin/orbit_analyser.cpp#L59-L59  https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/ksp_plugin/orbit_analyser.cpp#L86-L126  https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/physics/ephemeris_body.hpp#L522-L527 https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/integrators/symmetric_linear_multistep_integrator_body.hpp#L26-L43  https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/integrators/symmetric_linear_multistep_integrator_body.hpp#L278-L317  https://github.com/mockingbirdnest/Principia/blob/cc26d0fd2171b0fa4bc0ee1249759e1509deab4c/integrators/symplectic_runge_kutta_nystr%C3%B6m_integrator_body.hpp#L25-L48

**Comment by pleroy** [comment] 2021-01-23 10:57
The other crashes have exactly the same stack, just with different times in the failure message.

**Comment by VincentThacker** [comment] 2021-01-24 04:40
I am having the same issue. Here are my log files:
[ERROR.20210123-205135.12932.log](https://github.com/mockingbirdnest/Principia/files/5861579/ERROR.20210123-205135.12932.log)
[FATAL.20210123-205957.12932.log](https://github.com/mockingbirdnest/Principia/files/5861580/FATAL.20210123-205957.12932.log)
[INFO.20210123-205135.12932.log](https://github.com/mockingbirdnest/Principia/files/5861581/INFO.20210123-205135.12932.log)
[WARNING.20210123-205135.12932.log](https://github.com/mockingbirdnest/Principia/files/5861582/WARNING.20210123-205135.12932.log)

**Comment by eggrobin** [comment] 2021-01-24 15:50
I have reproduced the issue, (with journaling on even), by setting the plan length of an empty flight plan to something small but nonzero (I suspect something small enough that the thousandth substep used by the analyser to get a progress bar does not increment time).

We may want to change the ephemeris so that it does nothing when flowing an instance to the present. However, we wasted a lot of time trying to make sense of the logic of the integrators when it comes to dealing with mixed `Instant` and `DoublePrecision<Instant>`; some of it seems wrong. We should clean that up so that we can figure out whether it is correct—and sort out what we want the contract to be in the process.

**Comment by daantimmer** [comment] 2021-01-24 18:10
I take it from your response that a workaround, for now, would be to first increase the plan length and only then change the tangent?

**Comment by eggrobin** [comment] 2021-01-24 18:27
> I take it from your response that a workaround, for now, would be to first increase the plan length and only then change the tangent?

Yes, the issue is caused by the last coast of the flight plan becoming very short. Just make the plan very long (the maximal step count prevents that from catastrophically affecting performance, the « timed out » warning is largely ignorable).

The issue will be fixed in Gödel.

**Closed** 2021-01-25 00:02 UTC
Labels: bug
