### ISSUE TITLE
KSP crashes when starting a new RO/RP-0 career game

### ISSUE THREAD

**Issue by rsparkyc** [mockingbirdnest/Principia#1408] opened 2017-05-28 03:06 UTC
Using RO 11.5.0, on a mac (built from lamont).  Created a new save. 
Getting the following error when trying to go to the space center from the main menu:
```
F0527 22:50:34.499806 52753344 date_time_body.hpp:957] Check failed: contains(str, size, '-') == contains(str, size, ':')
```

Logs attached: [Archive.zip](https://github.com/mockingbirdnest/Principia/files/1033937/Archive.zip)

**Comment by pleroy** [comment] 2017-05-28 10:41
Yes, there was a bug in the initial cut of the Catalan release.  We quickly fixed the "official" binary but people building from the `2017052520-Catalan` tag will run into it.

The fix is in #1399 and the good news is that you can fix it yourself in your install: go to `GameData/Principia/real_solar_system` and edit the text file `initial_state_jd_2433282_500000000.cfg` to apply the first change in commit 6261bdcb4e7aff5f2423a33d9c39d15a244ba858, i.e., change the third line to read:
```
  solar_system_epoch = JD2433282.500000000
```

@lamont-granquist: it would be cool if you could fix your Mac build with the change above.

**Comment by rsparkyc** [comment] 2017-05-28 13:40
Awesome, trying that now.  Thanks!  Feel free to close this.

**Comment by lamont-granquist** [comment] 2017-05-28 16:33
I'll have a new build up soon with that cherry-pick

**Comment by pleroy** [comment] 2017-05-28 17:27
Closing since the issue is now resolved.  Thanks all.

**Closed by pleroy** 2017-05-28 17:27 UTC
Labels: bug
