### ISSUE TITLE
Crash due to `CHECK(v2.WillKeepPart(part2))`

### ISSUE THREAD

**Issue by rnlahaye** [mockingbirdnest/Principia#3339] opened 2022-03-13 00:01 UTC
I recently experienced a crash after decoupling. Here is the relevant section of the logs (the full error log is [attached](https://github.com/mockingbirdnest/Principia/files/8238720/INFO.20220312-112310.36217.log)):
```
I0312 15:48:34.647652 41928192 ksp_plugin_adapter.cs:1316] Reporting collision with collider SC-ENG-MOUNT-SKELETAL-M-Collider3 (0)
I0312 15:48:34.647687 41928192 plugin.cpp:564] Collision between ROT-RingDecoupler (D297F2F1) and ROT-BalloonTank-New (20C61FFF)
    @        0x5e1d26d5f  google::LogMessageFatal::~LogMessageFatal()
    @        0x5e1d23009  google::LogMessageFatal::~LogMessageFatal()
    @        0x5e19ee7df  principia::ksp_plugin::internal_plugin::Plugin::ReportPartCollision()
    @        0x5e1914998  principia__ReportPartCollision
F0312 15:48:34.647722 41928192 plugin.cpp:571] Check failed: v2.WillKeepPart(part2) ROT-BalloonTank-New (20C61FFF) will vanish
```
This seems to be `ksp_plug/plugin.cpp:571`.

Here `ROT-BalloonTank-New` is the rocket and `ROT-RingDecoupler` is the decoupler. I accidentally decoupled the wrong side of the decoupler (the rocket was released but the decoupler remained attached to my probe). When I subsequently detached the correct side, the decoupler flew off and eventually crashed into the rocket, resulting in the CHECK-failure.

I will try to get a journal.

**Comment by rnlahaye** [comment] 2022-03-13 02:12
I was unable to get a journal.

**Comment by pleroy** [comment] 2022-04-25 15:43
Might be a duplicate of #3219.

**Comment by pleroy** [comment] 2022-12-18 11:20
Closing as we have not heard of this bug after https://github.com/mockingbirdnest/Principia/pull/3349.

**Closed by pleroy** 2022-12-18 11:20 UTC
