### ISSUE TITLE
unable to load .dll files

### ISSUE THREAD

**Issue by glareof152** [mockingbirdnest/Principia#2334] opened 2019-09-22 10:27 UTC
I installed the vc correctly and when I run the game it shows this.
The Principia DLL failed to load.
An unknown error occurred; detected OS Microsoft Windows NT 10.0.17134.0 64-bit; tried loading dll at 'GameData\Principia\x64\principia.dll'. Note that the Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.22.27821 are required.
Before install vc
![screenshot0](https://user-images.githubusercontent.com/38170753/65385878-73294d00-dd66-11e9-9c42-5e030f125912.png)
after
![screenshot1](https://user-images.githubusercontent.com/38170753/65385882-86d4b380-dd66-11e9-9121-060a608a039e.png)

ksp.log:
`[EXC 19:12:09.673] DllNotFoundException: GameData/Principia/x64/principia.dll
	principia.ksp_plugin_adapter.Log.InitGoogleLogging ()
	principia.ksp_plugin_adapter.Loader.LoadPrincipiaDllAndInitGoogleLogging ()
	UnityEngine.Debug:LogException(Exception)
	principia.ksp_plugin_adapter.Loader:LoadPrincipiaDllAndInitGoogleLogging()
	principia.ksp_plugin_adapter.PrincipiaPluginAdapter:.ctor()
	UnityEngine.GameObject:AddComponent(Type)
	ScenarioRunner:AddModule(String)
	ScenarioRunner:AddModule(ConfigNode)
	ProtoScenarioModule:Load(ScenarioRunner)
	ScenarioRunner:LoadModules(List`1)
	ScenarioRunner:SetProtoModules(List`1)
	Game:Load()
	<Start>c__Iterator0:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
[ERR 19:12:09.674] The Principia DLL failed to load.
An unknown error occurred; detected OS Microsoft Windows NT 10.0.17134.0 64-bit; tried loading dll at 'GameData\Principia\x64\principia.dll'. Note that the Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.22.27821 are required.

[ERR 19:12:09.772] Exception loading ScenarioModule PrincipiaPluginAdapter: System.DllNotFoundException: GameData/Principia/x64/principia.dll
  at (wrapper managed-to-native) principia.ksp_plugin_adapter.Interface:SetBufferedLogging (int)
  at principia.ksp_plugin_adapter.Log.SetBufferedLogging (Int32 max_severity) [0x00000] in <filename unknown>:0 
  at principia.ksp_plugin_adapter.MainWindow.Load (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at BaseFieldList.Load (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ScenarioModule.Load (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ScenarioRunner.AddModule (.ConfigNode node) [0x00000] in <filename unknown>:0 `

**Comment by pleroy** [comment] 2019-09-22 11:56
Probably a duplicate of #2297, which will be fixed in the next version.

**Comment by glareof152** [comment] 2019-09-22 12:55
now works well

**Closed** 2019-09-22 12:54 UTC
Labels: duplicate
