### ISSUE TITLE
KSP CTDs when trying to plot very long flight plans (over 10000 days)

### ISSUE THREAD

**Issue by panourgue** [mockingbirdnest/Principia#1614] opened 2017-10-24 08:45 UTC
Logs are here: https://gist.github.com/panourgue/1eec5db2c8f036808775eea81340c267

**Comment by pleroy** [comment] 2017-12-10 12:08
Decoded stack trace:

[`physics/continuous_trajectory_body.hpp:153`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/physics/continuous_trajectory_body.hpp#L153)
[`physics/ephemeris_body.hpp:949`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/physics/ephemeris_body.hpp#L949)
[`integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp:223`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/integrators/embedded_explicit_runge_kutta_nyström_integrator_body.hpp#L223)
[`physics/ephemeris_body.hpp:502`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/physics/ephemeris_body.hpp#L502)
[`ksp_plugin/flight_plan.cpp:362`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/ksp_plugin/flight_plan.cpp#L362)
[`ksp_plugin/flight_plan.cpp:163`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/ksp_plugin/flight_plan.cpp#L163)
[`ksp_plugin/interface_flight_plan.cpp:484`](https://github.com/mockingbirdnest/Principia/blob/549227645d17aff78fbd2b5b45daa0df15190609/ksp_plugin/interface_flight_plan.cpp#L484)

**Comment by pleroy** [comment] 2017-12-10 16:27
From the stack and the error message, this bug seems to be the same as #1595, which was present in Chasles (the version you were using at the time of the crash) and fixed in 陈景润.  I am going to close this issue as a duplicate.  If somehow you reproduce the same crash in 陈景润 or later, we would of course be very interested to hear about it.

**Closed by pleroy** 2017-12-10 16:27 UTC
Labels: bug, duplicate
