### ISSUE TITLE
Game crashes when opening map view from vessels orbiting Minmus, or clicking on them in the tracking station

### ISSUE THREAD

**Issue by columbus15** [mockingbirdnest/Principia#3332] opened 2022-02-17 19:49 UTC
Good morning, I have been encountering an error after doing an Apollo-style Minmus landing in the stock solar system in a science save. When attempting to switch back to the command module in orbit through the tracking staion, the game freezes, then crashes without any message (essentially, closes itself). Ascending to orbit in the lander and then switching to map view to create a flight plan crashes the game instantly. A satellite from an earlier mission orbiting Minmus produces the same result.
I have multiple part mods such as BDB, and environment mods like Parallax and EVE. The solar system is the stock one and not unmodified, but all vessels this occurs with contained modded parts from BDB. 

All files relevant are [in this gist here.](https://gist.github.com/columbus15/0d9aa0a83136cfaa0c4692f3310c3b81)

I upgraded from Hardy and played on the new release multiple times before this crash occurred, and it does not seem to occur with Kerbin or the Mun or interplanetary space; I have not tested other planets.
In the stderr file, I can see something about a duplicated time mismatch, and googling about this in context with KSP brought me nothing. I hope this can be helped :)

**Comment by pleroy** [comment] 2022-02-17 21:00
Thank you for reporting.  From the look of your logs it seems that some data structure related to trajectories got corrupted.  However, there is not enough information for us to figure out how it got into that state.

Is this a problem that is reproducible?  If so, could you provide us with a *journal* (instructions [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#journaling))?  That would help us trace how/why/where the corruption happened.

**Comment by pleroy** [comment] 2022-02-20 12:14
I was able to reproduce the crash using the above journal, although things seem somewhat nondeterministic.  No idea what's happening yet.

Decoded strack trace:
 https://github.com/mockingbirdnest/Principia/blob/de95343225da7252d37a0108fed5ad73b9d0f2aa/ksp_plugin/interface_planetarium.cpp#L206-L234  https://github.com/mockingbirdnest/Principia/blob/de95343225da7252d37a0108fed5ad73b9d0f2aa/ksp_plugin/vessel.cpp#L356-L382  https://github.com/mockingbirdnest/Principia/blob/de95343225da7252d37a0108fed5ad73b9d0f2aa/ksp_plugin/vessel.cpp#L935-L943  https://github.com/mockingbirdnest/Principia/blob/de95343225da7252d37a0108fed5ad73b9d0f2aa/physics/discrete_trajectory_body.hpp#L396-L458

**Comment by pleroy** [comment] 2022-02-21 20:49
We have an empty segment (segment 472) in the middle of the trajectory for vessel `Sarnus II CF (Hermes I) Ship (15f6cf28-fc3e-4997-9ab4-93de951ab9c2)`.  That's a violation of our invariants: empty segments are fine at the beginning of trajectories, not in the middle.

How did this come to be?  This segment is the one immediately before the beginning of the "explicitly stored" part of the trajectory.  We conjecture that it is non-collapsible, so it should be rebuilt from a checkpoint.  However, there is no checkpoint matching the end time of that segment, `2000-10-24T16:27:13,1125793159008026 (TT)` (that time falls between checkpoints 225 and 226).  Normally we should always take a checkpoint when creating a non-collapsible segment, but there is worrisome code here: https://github.com/mockingbirdnest/Principia/blob/5f938415f207138b134b530d56ff8fe28ced8042/ksp_plugin/vessel.cpp#L195-L218
Notice how we skip creating the checkpoint if there is one at the same time, but we still create a segment.

This is somewhat inconsistent, but wouldn't be a disaster if there wasn't a nasty interaction with `WriteToMessage`: if given an iterator that designates a time at which a 1-point segment (or several) exists, `WriteToMessage` skips these 1-point segments and starts writing at the first segment that has multiple points.  The skipped 1-point segments will be reconstructed by integration (if they are collapsible) or from a checkpoint (if they are not).  The problem here is that we don't have a checkpoint (because of the above code) so we have no way to reconstruct the missing segment.

Having written this I am not completely sure how it should be fixed.  More thought will be needed...

**Closed** 2022-03-09 22:58 UTC
