### ISSUE TITLE
Principia can't generate gravity models when stock planets are scaled with Sigma Dimension (REPOSTED, JUST HEAR ME OUT)

### ISSUE THREAD

**Issue by Starcatcher2009** [mockingbirdnest/Principia#3744] opened 2023-08-17 14:20 UTC
Just hear me out. @pleroy 
"Plock" is an object in Outer Planets Mod. As you might have known, OPM works PERFECTLY fine with Principia.
If OPM is not installed, Principia would (unsuccessfully) load Eeloo after Kerbol.

**Comment by eggrobin** [comment] 2023-08-17 14:28
GitHub issues are not a chat app, they are a way to track the work we are doing. Under no circumstances is it ever appropriate to knowingly file duplicate issues. In addition, you have already discussed this matter on Discord. There was no use to filing the first issue to start with; since you clearly fail to understand the documentation we provide, you could ask for clarifications on Discord instead, where you might get them from others instead of wasting our time.

I will not tolerate more of this utter disrespect for our very scarce time.

Closed as duplicate of #3743.

**Closed by eggrobin** 2023-08-17 14:28 UTC
