### ISSUE TITLE
Extremely low performance near/at-the-surface-of Pluto.

### ISSUE THREAD

**Issue by Mirviy** [mockingbirdnest/Principia#3378] opened 2022-06-16 15:45 UTC
Game lags when time warp higher than 100x, and FPS drops to 1 when time warp at 10000x.
If I go to Tracking Station and do time warp, performance is good.
I don't know what is going wrong. I can upload a save file if needed.

Logs are filled with lines like following when time warp.
I0616 23:34:21.047646 17688 vessel.cpp:1006] Prognostication from 2112-07-16T09:58:27,5679721832275391 (TT) finished at 2112-07-16T18:49:44,9525532722473145 (TT) with ABORTED: Reached maximum step count 256 at time 2112-07-16T18:49:44,9525532722473145 (TT); requested t_final is 2112-07-29T09:20:00,0000000000000000 (TT). for Pluto-2 着陆器 (8bc5eb2a-9751-4b49-8193-919cfa77637d)

-------

(Also this issue is absent in Charon's SOI. )

**Comment by pleroy** [comment] 2022-06-16 19:55
Please give us your log files as explained [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#windows-dialog-box-or-sigabrt).  Also, if the problem is reproducible, it would be nice to give us a journal, see [here](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#journaling) for instructions.

Your save is probably not going to help.

**Comment by Mirviy** [comment] 2022-06-17 15:30
This issue is reproducible with fresh new game (only RSS + Principia installed).
1. Start new game, create a vessel (with some dv and control), and cheat to Charon's orbit.
2. Time warp in Charon's SOI is very smooth.
3. Maneuver to Pluto's SOI. Time warp is very laggy (better than in my 150-year-old carrier save but still notable).

I tested this and following are journals, logs, and save file.
https://bridge.kamine.cloud/files/Principia_PlutoLag_Journal+Log+Save.zip
(My test begins at 22:24:49, there are some extra lines in log file before the test.)

**Comment by pleroy** [comment] 2022-11-27 15:53
(Apologies for the late answer.)

You are running with verbose logging enabled.  Is that intentional?  I estimate that this will burn 25-30% of the CPU spitting out (at times) hundreds of messages per millisecond in the logs.

Please disable verbose logging.  If the problem persists, please send us another journal so that we have a cleaner execution profile to investigate.

**Comment by pleroy** [comment] 2024-08-20 11:48
Closing as we never heard back.  Just don't run with verbose logging, you won't like the results.

**Closed by pleroy** 2024-08-20 11:48 UTC
