### ISSUE TITLE
hard crash with the newest update

### ISSUE THREAD

**Issue by DanielFabian** [mockingbirdnest/Principia#3689] opened 2023-06-18 13:47 UTC
I just updated to the newest principia and I'm experiencing a hard crash. No logs or anything. 

To repro it, pick Minmus-Kerbin as the plotting frame, start a flight plan and just add a manoeuvre. The moment I click add manoeuvre it crashes immediately.

![image](https://github.com/mockingbirdnest/Principia/assets/1929340/e99364f9-e9af-49e2-a36a-80aa2a4451ae)

Please tell me if you need more data to repro.

**Comment by eggrobin** [comment] 2023-06-18 14:01
It looks like I can reproduce an issue that looks like this, but

> No logs or anything.

I am getting a FATAL log. Have you looked at the [FAQ section on reporting bugs](https://github.com/mockingbirdnest/Principia/wiki/Installing,-reporting-bugs,-and-frequently-asked-questions#reporting-bugs) and checked in the right place for the logs?

**Comment by DanielFabian** [comment] 2023-06-18 14:05
I apologize, I did not. Here's the fatal log:

Log file created at: 2023/06/18 15:33:18
Running on machine: DANY-PC
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   00007FF9107544FF  	google::LogMessageFatal::~LogMessageFatal [0x00007FF9107544FE+46]
    @   00007FF8B9C8B263  	principia__LogFatal [0x00007FF8B9C8B262+322]
    @   0000026CFBFD7F19  	(No symbol) [0x0000026CFBFD7F18]
F0618 15:33:18.237845 33460 reference_frame_selector.cs:148] Naming parent-direction rotating frame of root body

**Comment by eggrobin** [comment] 2023-06-18 16:21
We’ll publish an updated 伊藤 release in a few hours.

**Closed** 2023-06-19 19:06 UTC
